#!/bin/bash
mkdir -p build/gnu
make
APLX=spinjpeg.aplx
if [ -e "$APLX" ]
then
    mkdir -p ../bin
    mv "$APLX" ../bin
    rm -rf build
    echo
    echo "[INFO] The aplx is moved into ../bin/"$APLX
fi
