#!/bin/bash
mkdir -p build/gnu
make
APLX=mSpinJPEGenc.aplx
if [ -e "$APLX" ]
then
    mkdir -p ../../../bin
    mv "$APLX" ../../../bin/
    rm -rf build
    echo
    echo "[INFO] The aplx is moved into ../../../bin/"$APLX
else
    echo "[ERR] Compilation error"
fi
